Update templates/terraform-custom-azurerm/template.yaml
Co-authored-by: Pasquale De Vita <59291437+pasqualedevita@users.noreply.github.com>

diff --git a/templates/terraform-custom-azurerm/template.yaml b/templates/terraform-custom-azurerm/template.yaml
--- a/templates/terraform-custom-azurerm/template.yaml
+++ b/templates/terraform-custom-azurerm/template.yaml
@@ -25,5 +25,9 @@ steps:
       export TERRAFORM_CACHE_DIR='.terraform.d/plugin-cache/registry.terraform.io/hashicorp/azurerm/${{ parameters.AZURERM_PROVIDER_CUSTOM_VERSION }}/linux_amd64'
       mkdir -p ~/${TERRAFORM_CACHE_DIR}
       wget ${{ parameters.AZURERM_PROVIDER_CUSTOM_URL }}/${{ parameters.AZURERM_PROVIDER_CUSTOM_RELEASE }}/terraform-provider-azurerm 2> /dev/null
+      if [ $? -ne 0 ]; then
+        echo "wget FAIL"
+        exit 1
+      fi
       chmod +x terraform-provider-azurerm
       mv terraform-provider-azurerm ~/${TERRAFORM_CACHE_DIR}/terraform-provider-azurerm_v${{ parameters.AZURERM_PROVIDER_CUSTOM_VERSION }}
