[#176591264] added test - it should create a PR

diff --git a/.devops/test-pipelines.yaml b/.devops/test-pipelines.yaml
--- a/.devops/test-pipelines.yaml
+++ b/.devops/test-pipelines.yaml
@@ -109,7 +109,6 @@ stages:
 
 
 
-
   - stage: Test_ClientSDKGeneration
     dependsOn: []
     jobs:
@@ -192,3 +191,32 @@ stages:
             yarn test
           displayName: 'it should call the api and receive the expected result'
           workingDirectory: .devops/__tests__/client-sdk-generation/test-sdk/client_src
+
+
+
+  - stage: Test_Yarn_Lock_File_Upgrade
+    jobs:
+      - job: do_yarn_lock_upgrade   
+        steps:
+        - template: ../../templates/yarn-lock-upgrade/template.yaml
+          parameters:
+            projectDir: .devops/__tests__/sample-yarn-upgrade
+
+        - script: |
+            #setup hub CLI
+            echo "github.com: 
+            - user: $GITHUB_USERNAME
+              oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
+
+            PR_NUMBER=`hub pr list | grep "\[Yarn.lock Upgrade]" | awk '{print $1}' | sed 's/#//'`
+            echo "##vso[task.setvariable variable=pr_number]$PR_NUMBER"
+
+            echo "==> PR $PR_NUMBER"
+            if [[ -n "$PR_NUMBER" ]]; then exit 0; else echo "PR Not Found"; exit 1; fi
+
+          displayName: 'it should open a PR'
+      
+        - script: |
+            hub issue update $(pr_number) -s closed   
+            echo "" > ~/.config/hub
+          displayName: Cleanup
