[#176591264] close older pr and create a new one

diff --git a/.devops/test-pipelines.yaml b/.devops/test-pipelines.yaml
--- a/.devops/test-pipelines.yaml
+++ b/.devops/test-pipelines.yaml
@@ -198,88 +198,88 @@ stages:
 
   - stage: Test_Yarn_Lock_File_Upgrade
     dependsOn: []
-    # condition: contains(variables['build.sourceBranch'], 'lockfile-auto-upgrade-')
+    condition: contains( variables.system.pullRequest.sourceBranch , 'lockfile-auto-upgrade-') 
     
     jobs:
-
-      - job: do_yarn_lock_upgrade_test_1
-        pool:
-          vmImage: ubuntu-latest   
-        steps:
-          - script: |
-              echo "1: $(system.pullRequest.sourceBranch)"
-              echo "2: ${{ contains( variables.system.pullRequest.sourceBranch , 'lockfile-auto-upgrade-') }}"  
-
-
-            displayName: 'Test'
 
       # - job: do_yarn_lock_upgrade_test_1
       #   pool:
       #     vmImage: ubuntu-latest   
       #   steps:
+      #     - script: |
+      #         echo "1: $(system.pullRequest.sourceBranch)"
+      #         echo "2: ${{ contains( variables.system.pullRequest.sourceBranch , 'lockfile-auto-upgrade-') }}"  
 
-      #   #Call the Yarn.lock updated the first time
-      #   - template: ../templates/yarn-lock-upgrade/template.yaml
-      #     parameters:
-      #       projectDir: .devops/__tests__/sample-yarn-upgrade
-      #       isTest: true
 
-      #   - script: |
-      #       #setup hub CLI
-      #       echo "github.com: 
-      #       - user: $GITHUB_USERNAME
-      #         oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
+      #       displayName: 'Test'
 
-      #       PR_NUMBER=`hub pr list | grep "\[Yarn.lock Upgrade\]" | awk '{print $1}' | sed 's/#//'`
+      - job: do_yarn_lock_upgrade_test_1
+        pool:
+          vmImage: ubuntu-latest   
+        steps:
 
-      #       echo "==> PR $PR_NUMBER"
-      #       if [[ -n "$PR_NUMBER" ]]; then exit 0; else echo "PR Not Found"; exit 1; fi
-      #     displayName: 'it should open a PR'
+        #Call the Yarn.lock updated the first time
+        - template: ../templates/yarn-lock-upgrade/template.yaml
+          parameters:
+            projectDir: .devops/__tests__/sample-yarn-upgrade
+            isTest: true
+
+        - script: |
+            #setup hub CLI
+            echo "github.com: 
+            - user: $GITHUB_USERNAME
+              oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
+
+            PR_NUMBER=`hub pr list | grep "\[Yarn.lock Upgrade\]" | awk '{print $1}' | sed 's/#//'`
+
+            echo "==> PR $PR_NUMBER"
+            if [[ -n "$PR_NUMBER" ]]; then exit 0; else echo "PR Not Found"; exit 1; fi
+          displayName: 'it should open a PR'
         
-      #   - script: | 
-      #       echo "" > ~/.config/hub
-      #     displayName: Cleanup Tests 2
+        - script: | 
+            echo "" > ~/.config/hub
+          displayName: Cleanup Tests 2
 
-      # - job: do_yarn_lock_upgrade_test_2
-      #   dependsOn: do_yarn_lock_upgrade_test_1
-      #   pool:
-      #     vmImage: ubuntu-latest   
-      #   steps:
+      - job: do_yarn_lock_upgrade_test_2
+        dependsOn: do_yarn_lock_upgrade_test_1
+        pool:
+          vmImage: ubuntu-latest   
+        steps:
 
-      #   #Call it again, when a PR is open
-      #   - template: ../templates/yarn-lock-upgrade/template.yaml
-      #     parameters:
-      #       projectDir: .devops/__tests__/sample-yarn-upgrade
-      #       isTest: true
+        #Call it again, when a PR is open
+        - template: ../templates/yarn-lock-upgrade/template.yaml
+          parameters:
+            projectDir: .devops/__tests__/sample-yarn-upgrade
+            isTest: true
 
-      #   - script: |
-      #       #setup hub CLI
-      #       echo "github.com: 
-      #       - user: $GITHUB_USERNAME
-      #         oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
+        - script: |
+            #setup hub CLI
+            echo "github.com: 
+            - user: $GITHUB_USERNAME
+              oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
 
-      #       OPEN_PR_NR=`hub pr list | grep "\[Yarn.lock Upgrade\]" | wc -l`
-      #       echo "PR open: $OPEN_PR_NR"
-      #       if [[ "$OPEN_PR_NR" == 2 ]]; then echo "It opened a new PR instead of using the same one"; exit 1; else exit 0; fi
-      #     displayName: 'it should not open a new PR, if present'
+            OPEN_PR_NR=`hub pr list | grep "\[Yarn.lock Upgrade\]" | wc -l`
+            echo "PR open: $OPEN_PR_NR"
+            if [[ "$OPEN_PR_NR" == 2 ]]; then echo "It opened a new PR instead of using the same one"; exit 1; else exit 0; fi
+          displayName: 'it should not open a new PR, if present'
         
-      #   - script: | 
-      #       echo "" > ~/.config/hub
-      #     displayName: Cleanup Tests 2
+        - script: | 
+            echo "" > ~/.config/hub
+          displayName: Cleanup Tests 2
 
-      # - job: Cleanup_Tests
-        # dependsOn: do_yarn_lock_upgrade_test_2
-        # pool:
-        #   vmImage: ubuntu-latest   
-        # steps:
+      - job: Cleanup_Tests
+        dependsOn: do_yarn_lock_upgrade_test_2
+        pool:
+          vmImage: ubuntu-latest   
+        steps:
         
-        # - script: |
-        #     #setup hub CLI
-        #     echo "github.com: 
-        #     - user: $GITHUB_USERNAME
-        #       oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
+        - script: |
+            #setup hub CLI
+            echo "github.com: 
+            - user: $GITHUB_USERNAME
+              oauth_token: $(GITHUB_TOKEN)" > ~/.config/hub
 
-        #     PR_TO_DELETE_NR=`hub pr list | grep "\[Yarn.lock Upgrade\]" | awk '{print $1}' | sed 's/#//'`
-        #     hub issue update $PR_TO_DELETE_NR -s closed   
-        #     echo "" > ~/.config/hub
-        #   displayName: Cleanup Tests
+            PR_TO_DELETE_NR=`hub pr list | grep "\[Yarn.lock Upgrade\]" | awk '{print $1}' | sed 's/#//'`
+            hub issue update $PR_TO_DELETE_NR -s closed   
+            echo "" > ~/.config/hub
+          displayName: Cleanup Tests
